# Generated by Django 5.0.2 on 2024-02-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0002_experiment_sample_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
