# Generated by Django 5.0.2 on 2024-02-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0007_alter_experiment_experiment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='default_analysis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
