# Generated by Django 5.0.2 on 2024-02-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0010_alter_experiment_vendor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'ordering': ['id'], 'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('diann-create', 'DIA-NN Search (create spectral library)'), ('diann-spectral', 'DIA-NN Search (with spectral library)')], max_length=20),
        ),
    ]
