# Generated by Django 5.0.2 on 2024-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0012_folderwatchinglocation_network_folder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='generated_quant',
            field=models.ManyToManyField(blank=True, related_name='generated_quant_files', to='catapult.file'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='generating_quant',
            field=models.ManyToManyField(blank=True, related_name='quant_files', to='catapult.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='processing',
            field=models.BooleanField(default=False),
        ),
    ]
