# Generated by Django 5.0.2 on 2024-02-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0013_analysis_generated_quant_analysis_generating_quant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderwatchinglocation',
            name='ignore_terms',
            field=models.TextField(blank=True, default='DONOTPROCESS', null=True),
        ),
    ]
