# Generated by Django 5.0.2 on 2024-02-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0014_folderwatchinglocation_ignore_terms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folderwatchinglocation',
            old_name='ignore_terms',
            new_name='ignore_term',
        ),
    ]
