# Generated by Django 5.0.2 on 2024-02-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0015_rename_ignore_terms_folderwatchinglocation_ignore_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='spectral_library',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='fasta_file',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
