# Generated by Django 5.0.2 on 2024-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0020_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='folderwatchinglocation',
            name='extensions',
            field=models.TextField(blank=True, default='.raw,.wiff,.d,.mzML,.dia', null=True),
        ),
    ]
