# Generated by Django 5.0.2 on 2024-02-22 18:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0022_celerytasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CeleryTasks',
            new_name='CeleryTask',
        ),
    ]
