# Generated by Django 5.0.2 on 2024-02-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0023_rename_celerytasks_celerytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='analysis_params',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
