# Generated by Django 5.0.2 on 2024-02-22 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0024_celerytask_analysis_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='celerytask',
            old_name='task_status',
            new_name='status',
        ),
    ]
