# Generated by Django 5.0.2 on 2024-03-01 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0025_rename_task_status_celerytask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('worker_params', models.JSONField(blank=True, null=True)),
                ('worker_status', models.CharField(max_length=20)),
                ('worker_hostname', models.CharField(db_index=True, max_length=200, unique=True)),
                ('folder_path_translations', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MSConvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('output_folder', models.TextField()),
                ('processing', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('log', models.TextField(blank=True, null=True)),
                ('commands', models.TextField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msconvert', to='catapult.experiment')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msconvert', to='catapult.file')),
            ],
        ),
    ]
