# Generated by Django 5.0.2 on 2024-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0027_alter_msconvert_experiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='celeryworker',
            name='worker_os',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
