# Generated by Django 5.0.2 on 2024-03-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0028_celeryworker_worker_os'),
    ]

    operations = [
        migrations.AddField(
            model_name='celerytask',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catapult.celeryworker'),
        ),
    ]
