# Generated by Django 5.0.6 on 2024-07-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0031_celeryworker_worker_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatapultRunConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config_file_path', models.TextField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_config', to='catapult.analysis')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_config', to='catapult.experiment')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
