# Generated by Django 5.0.6 on 2024-07-04 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0032_catapultrunconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catapultrunconfig',
            name='analysis',
        ),
        migrations.AddField(
            model_name='analysis',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis', to='catapult.catapultrunconfig'),
        ),
        migrations.AddField(
            model_name='catapultrunconfig',
            name='folder_watching_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='run_config', to='catapult.folderwatchinglocation'),
        ),
    ]
