# Generated by Django 5.0.6 on 2024-07-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0034_remove_analysis_fasta_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='total_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('protein_identified', models.IntegerField(blank=True, null=True)),
                ('precursor_identified', models.IntegerField(blank=True, null=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_summary', to='catapult.analysis')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result_summary', to='catapult.file')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
