# Generated by Django 5.0.7 on 2024-07-17 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0037_logrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecursorReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precursor_id', models.TextField()),
                ('gene_names', models.TextField(blank=True, null=True)),
                ('protein_group', models.TextField(blank=True, null=True)),
                ('proteotypic', models.BooleanField(default=False)),
                ('intensity', models.FloatField(blank=True, null=True)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='precursor_report_content', to='catapult.file')),
                ('result_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precursor_report_content', to='catapult.resultsummary')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProteinGroupReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gene_names', models.TextField(blank=True, null=True)),
                ('protein_group', models.CharField(max_length=200)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='protein_group_report_content', to='catapult.file')),
                ('result_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protein_group_report_content', to='catapult.resultsummary')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
