# Generated by Django 5.0.7 on 2024-07-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0038_precursorreportcontent_proteingroupreportcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteingroupreportcontent',
            name='intensity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
