# Generated by Django 5.0.7 on 2024-07-18 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0039_proteingroupreportcontent_intensity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsummary',
            old_name='log_file',
            new_name='stats_file',
        ),
    ]
