# Generated by Django 5.0.7 on 2024-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0040_rename_log_file_resultsummary_stats_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultsummary',
            name='log_file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
