# Generated by Django 5.0.7 on 2024-07-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0041_resultsummary_log_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='analysis_name',
            new_name='analysis_path',
        ),
    ]
