# Generated by Django 5.0.7 on 2024-07-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0042_rename_analysis_name_analysis_analysis_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_path',
            field=models.TextField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='commands',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
