# Generated by Django 5.0.7 on 2024-07-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catapult', '0043_alter_analysis_analysis_path_alter_analysis_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='analysis_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
