FROM node:20-bullseye-slim

EXPOSE 80
WORKDIR /app
RUN apt update
RUN apt -y upgrade
RUN apt install -y git
RUN git clone https://github.com/noatgnu/catapultNG.git
WORKDIR /app/catapultNG
RUN npm install
RUN npm run build

FROM nginx:latest

COPY --from=0 /app/catapultNG/dist/browser /usr/share/nginx/html

EXPOSE 80
